version: 3

vars:
  root_dir:
    sh: git rev-parse --show-toplevel
  golang_lint_version: v1.51.2
  golang_version: 1.21.4

tasks:
  default:
    desc: Default task.
    cmds:
      - echo "Please enter a task name or use -l / --list-all to list all available tasks"
    silent: true

  common/vendor:
    desc: Run go mod vendor.
    cmds:
      - |
        cd {{ .root_dir }} && go mod tidy
        if [ -d "{{ .root_dir }}/vendor" ]; then
          echo "{{ .root_dir }}/vendor folder already exist"
        else
          go mod vendor
        fi
    silent: true

  build/base:
    desc: Build binary base command.
    deps:
      - common/vendor
    env:
      BINARY_NAME: netsurf
    cmds:
      - |
        cd {{ .root_dir }} && mkdir -p {{ .root_dir }}/bin && \
        go build -ldflags="-w -s" -o {{ .root_dir }}/bin/${BINARY_NAME} ./cmd

  build/local:
    desc: Build app on local.
    env:
      CGO_ENABLED: 1
    cmds:
      - task: build/base
        vars: { BINARY_NAME: "netsurf_dev" }
