ARG GO_VERSION

FROM golang:${GO_VERSION}-alpine as builder-arm64
RUN apk update && apk add --no-cache build-base gcc gcc-aarch64-none-elf wireless-tools-dev linux-headers curl git
WORKDIR /go/src

FROM golang:${GO_VERSION}-alpine as builder-amd64
RUN apk update && apk add --no-cache curl git
WORKDIR /go/src

FROM builder-${TARGETARCH}
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin \
    && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.55.2 \
    && go install go.uber.org/nilaway/cmd/nilaway@latest
