name: Build CI/CD images

on:
  workflow_dispatch:
  push:
    paths:
      - '.infra/images/*'

env:
  IMAGE_NAME: chelyshkin/netsurf-ci

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find modified Dockerfiles
        id: find-files
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.infra/images.*Dockerfile' || echo "")
          echo "Modified files: $files"
          echo "::set-output name=modified_files::$files"

      - name: Create matrix
        id: set-matrix
        run: |
          files="${{ steps.find-files.outputs.modified_files }}"
          matrix="["
          for file in $files; do
            filename=$(basename "$file" | sed 's/Dockerfile-//;s/Dockerfile//;s/\./-/g') # Измените это согласно вашим правилам именования
            arch="$(echo $file | grep -oE '(amd64|arm64)')" # Extract architecture from filename
            matrix="$matrix{\"dockerfile\":\"$file\", \"tag\":\"$filename\"},"
          done
          matrix="${matrix%,}]"
          echo "Matrix: $matrix"
          echo "::set-output name=matrix::$matrix"

  build-and-push:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Go version from go.mod
        run: |
          echo "GO_VERSION=$(sed -n -e 's/^go //p' go.mod)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          platforms: linux/${{ matrix.arch }}
          build-args: GO_VERSION=${{ env.GO_VERSION }}
          target: builder-${{ matrix.arch }}
