name: Build CI/CD images

on:
  workflow_dispatch:
  push:
    paths:
      - '.infra/images/*'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find modified files in the latest commit
        id: find-files
        run: |
          echo "Listing changes in the latest commit..."
          files=$(git show --name-only --pretty=format: | grep '^.infra/images/' || echo "")
          echo "Modified files: $files"
          echo "::set-output name=modified_files::$files"

      - name: Create matrix
        id: set-matrix
        run: |
          files="${{ steps.find-files.outputs.modified_files }}"
          matrix="["
          for file in $files; do
            if [ -n "$file" ]; then
              filename=$(basename "$file" | sed 's/\./-/g')
              matrix="$matrix{\"dockerfile\":\"$file\", \"tag\":\"$filename\"},"
            fi
          done
          matrix="${matrix%,}]"
          echo "Generated matrix: $matrix"
          echo "::set-output name=matrix::$matrix"

  build-and-push:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          docker buildx build --file ${{ matrix.dockerfile }} \
            --tag ${{ secrets.AWS_ECR_REPOSITORY }}:${{ matrix.tag }} \
            --platform linux/amd64,linux/arm64 \
            --push .
