name: Docker Build and Push

on:
  push:
    branches: [ ci-cd ]
#    paths:
#      - './images/Dockerfile-ci'
#      - 'go.mod'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Go version from go.mod
        id: go-version
        run: |
          echo "GO_VERSION=$(sed -n -e 's/^go //p' go.mod)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/Dockerfile-ci
          push: true
          tags: chelyshkin/netsurf-ci:latest
          platforms: linux/amd64,linux/arm64
          build-args: GO_VERSION=${{ env.GO_VERSION }}
